version: '3.3'
volumes:
  data_tccalexiajulia:
services:
 
  db:
    image: mysql:latest
    volumes:
      - data_tccalexiajulia:/var/lib/mysql
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

    environment:
      - MYSQL_USER=user
      - MYSQL_DATABASE=sacaa
      - MYSQL_PASSWORD=12345
      - MYSQL_ROOT_PASSWORD=root
    
    ports:
      - "3306:3306"
  
  node:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: npm start
    environment:
        - DEV=1
    volumes:
      - .:/app
      - "/etc/timezone:/etc/timezone:"
      - "/etc/localtime:/etc/localtime:"

    ports:
      - "3000:3000"
    depends_on:
      - db 
